name: ujap
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_keyboard_visibility: ^5.0.3
  shared_preferences: ^2.0.7
  page_transition: ^2.0.2
  http: ^0.13.3
  image_picker: ^0.8.4+1
  sliding_up_panel: ^2.0.0+1
  intl: any
  dotted_decoration: ^2.0.0
  carousel_slider: ^4.0.0
  flushbar: ^1.10.4
  flutter_launcher_icons: ^0.9.2
  shimmer: ^2.0.0
  flutter_speech: ^2.0.0
  firebase_messaging: ^10.0.7
  firebase_analytics: ^8.0.3
  video_player: ^2.2.3
  chewie: ^1.2.2
  rxdart: ^0.27.2
  image_cropper: ^1.3.1
  dio: ^4.0.0
  flutter_slidable: ^0.6.0
  path_provider: ^2.0.4
  permission_handler: ^8.1.6
  external_path: ^1.0.1
  file_picker: ^4.1.1
  advance_pdf_viewer: ^2.0.0
  flutter_email_sender: ^5.0.2
  http_parser: ^4.0.0
  kt_dart: ^0.9.1
  grouped_list: ^4.1.0
  url_launcher: ^6.0.10
  firebase_core: ^1.6.0
  sqflite:
  flutter_pdfview: ^1.0.4
  cached_network_image: ^3.1.0
  modal_bottom_sheet: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/login_icons/
    - assets/home_icons/
    - assets/view_events_icons/
    - assets/messages_icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Google-bold
      fonts:
        - asset: fonts/GoogleSans-Bold.ttf
    - family: Google-BoldItalic
      fonts:
        - asset: fonts/GoogleSans-BoldItalic.ttf
    - family: Google-Italic
      fonts:
        - asset: fonts/GoogleSans-Italic.ttf
    - family: Google-Medium
      fonts:
        - asset: fonts/GoogleSans-Medium.ttf
    - family: Google-MediumItalic
      fonts:
        - asset: fonts/GoogleSans-MediumItalic.ttf
    - family: Google-Regular
      fonts:
        - asset: fonts/GoogleSans-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
